### ISSUE TITLE
Code release of AdaMPI

### ISSUE THREAD

**Issue by xingyi-li** [yxuhan/AdaMPI#1]
Hi, @yxuhan! Very impressive work on SIGGRAPH 2022! 

May I know when the code will be released?

Many thanks!

**Comment by xingyi-li** [comment]
Also, will the pretrained model be released?

**Comment by yxuhan** [comment]
Hi @xingyi-li , I plan to release the code in the next month, including the pretrained MPI generation model, and the inpainting network to generate the training data.
