### ISSUE TITLE
warp-back

### ISSUE THREAD

**Issue by chky1997** [yxuhan/AdaMPI#10]
Thank you for your great work!
I noticed that in your paper there is a warp-back synthesis using a NVS network after the inpainting network. But in stage2_dataset.py, there is only inpainting before output. Is the NVS network not released yet?

**Comment by yxuhan** [comment]
The pretrained NVS network (AdaMPI) is already released, see [here](https://github.com/yxuhan/AdaMPI/blob/master/doc/AdaMPI.md). We do not release the training code for the NVS network. The provided data loader in `stage2_dataset.py` can be integrated into the training loop of any other single-view view synthesis network.
