### ISSUE TITLE
关于合成的视点出现纹理现象

### ISSUE THREAD

**Issue by chenpaopao** [yxuhan/AdaMPI#13]
作者您好，我们使用预训练的模型合成新视点，在某些图片（连续单调的颜色区域）下出现纹路，且MPI层数越多，纹路颜色越不明显，但纹路越多。请问这个情况是MPI渲染的必然出现的吗？有没有一些方法可以解决or缓解该现象
![图片1](https://github.com/yxuhan/AdaMPI/assets/34935759/ef3b7f3d-a091-4bf3-b807-4d59c7cb6a5b)
![图片2](https://github.com/yxuhan/AdaMPI/assets/34935759/25e9d6a1-9b6f-4e64-93a0-47b101a566d1)

**Comment by GFENGG** [comment]
您好，请问预训练模型是怎么下载的呢，方便发一份么～
我邮箱是2482648525@qq.com
非常感谢

**Comment by chenpaopao** [comment]
https://drive.google.com/drive/folders/1NfXUlSTHc390YPkKSeddOghzl0W6q7wn?usp=sharing
