### ISSUE TITLE
How to produce a right eye photo?

### ISSUE THREAD

**Issue by WithAIGC** [yxuhan/AdaMPI#14]
If I input an image as the left eye image and generate the right eye image through your code, if the distance between the human eyes is 6.5 cm, how should I modify these parameters?
`def gen_translate_path(num_frames=2, r_x=0.065, r_y=0., r_z=0):
    poses = torch.eye(4).repeat(num_frames, 1, 1)
    poses[1, 0, 3] = r_x
    poses[1, 1, 3] = r_y 
    poses[1, 2, 3] = r_z
    return poses`
Here I set the pose of the camera:
`camera path pose:  tensor([[[ 1.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  1.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  1.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  1.0000]],

        [[ 1.0000,  0.0000,  0.0000, 0.0650],
         [ 0.0000,  1.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  1.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  1.0000]]])`
The difference between the two images I got is very small, and the left and right views cannot be combined.
I want to ask if I do this, is there a problem? @yxuhan

**Comment by yxuhan** [comment]
Hi, the unit of our camera system is not `cm`, so the x-translation 0.065 does not correspond to 6.5cm. You can first align the scale of our camera system to 'cm', then set 6.5cm as the translation.

**Comment by WithAIGC** [comment]
哈喽，您好，我用您提出的adampi用于左右视图合成，主题内容边缘出现伪影，这是什么原因导致的呢


------------------ Original ------------------
From: Yuxuan Han ***@***.***&gt;
Date: Wed,Jul 5,2023 10:54 PM
To: yxuhan/AdaMPI ***@***.***&gt;
Cc: WithAIGC ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [yxuhan/AdaMPI] How to produce a right eye photo? (Issue #14)





 
Closed #14 as completed.
