### ISSUE TITLE
What's the function of blend weights?

### ISSUE THREAD

**Issue by imlixinyang** [yxuhan/AdaMPI#15]
Hello author, I don't quite understand the purpose of pre-blending here. Could you provide an explanation?
https://github.com/yxuhan/AdaMPI/blob/08df9465af96913624460ea4bf40eb4f14b111e8/utils/utils.py#L70

**Comment by yxuhan** [comment]
Hi, the MPI rendering code is directly adapted from MINE.

My understanding is that, for the single-view view synthesis task, the goal is to inpaint the unseen regions in the source view. Such unseen contents cause the disocclusions in the novel view. For the regions that are visible in the source view, we expect them to be similar to the content on the source view. This blending strategy makes the seen regions more similar to the content on the source view.
