### ISSUE TITLE
变换矩阵K

### ISSUE THREAD

**Issue by okideal** [yxuhan/AdaMPI#16]
很棒的工作！
想问一下关于最后render里的变换矩阵K_src, K_tar，怎么调整能够控制视图的规则呢

**Comment by yxuhan** [comment]
K_src和K_tgt是相机的内参。如果想控制视角，需要变换外参，也就是`cam_ext`
https://github.com/yxuhan/AdaMPI/blob/08df9465af96913624460ea4bf40eb4f14b111e8/utils/utils.py#L75-L84
可以参考下面的函数来调整外参变换视角：
https://github.com/yxuhan/AdaMPI/blob/08df9465af96913624460ea4bf40eb4f14b111e8/utils/utils.py#L32-L39

**Comment by okideal** [comment]
明白了，感谢

**Comment by csyhping** [comment]
@yxuhan ， may I ask how I can modify your code snippet if I want to get the spiral paths like NERF? Thanks.
