### ISSUE TITLE
Basic zoom without circle effect

### ISSUE THREAD

**Issue by C00reNUT** [yxuhan/AdaMPI#22]
Hello,

may I ask you how and which parameters need to be changes to achieve simple zoom?

**Comment by yxuhan** [comment]
Hi, you can comment out the camera translation on the x and y axis, while only keeping the z-axis translation.

**Comment by C00reNUT** [comment]
Thank you! Would you be so kind to reference the file and code line?

**Comment by yxuhan** [comment]
https://github.com/yxuhan/AdaMPI/blob/125f7c23315afe8f33f7b799d7bfcc66a9990ab4/utils/utils.py#L36-L37

You can try to comment out these lines. I have not checked carefully; hope it should work.
