### ISSUE TITLE
Nan Error During Training

### ISSUE THREAD

**Issue by jiadingfang** [yxuhan/AdaMPI#7]
Hi,

Per your hint for training at https://github.com/yxuhan/AdaMPI/issues/4#issuecomment-1214975556, I used the same photometric losses in MINE to try to train AdaMPI from scratch on the downsampled LLFF dataset that MINE provides. However, I had Nan errors some time into the training (not immediately). Have you spotted any Nan errors in the training? Do you have any suggestions handling them?

Thanks,
JD

**Comment by yxuhan** [comment]
Rank loss and assign loss mentioned in our paper are important for training our network. If only use photometric loss, the training process would be unstable.

**Comment by jiadingfang** [comment]
Thanks for the suggestions! Questions about the depths in two regularization losses: are they (e.g. $D_s$, $d_i$) actual depths or normalized disparities?

**Comment by yxuhan** [comment]
They are normalized disparities.
